# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class BranchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/bank.Branch/Query',
                request_serializer=service__pb2.QueryInput.SerializeToString,
                response_deserializer=service__pb2.QueryOutput.FromString,
                )
        self.Deposit = channel.unary_unary(
                '/bank.Branch/Deposit',
                request_serializer=service__pb2.DepositInput.SerializeToString,
                response_deserializer=service__pb2.Output.FromString,
                )
        self.Withdraw = channel.unary_unary(
                '/bank.Branch/Withdraw',
                request_serializer=service__pb2.WithdrawInput.SerializeToString,
                response_deserializer=service__pb2.Output.FromString,
                )
        self.PropogateWithdraw = channel.unary_unary(
                '/bank.Branch/PropogateWithdraw',
                request_serializer=service__pb2.PropogateWithdrawInput.SerializeToString,
                response_deserializer=service__pb2.Output.FromString,
                )
        self.PropogateDeposit = channel.unary_unary(
                '/bank.Branch/PropogateDeposit',
                request_serializer=service__pb2.PropogateDepositInput.SerializeToString,
                response_deserializer=service__pb2.Output.FromString,
                )


class BranchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Query branch 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Deposit to branch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Withdraw from branch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropogateWithdraw(self, request, context):
        """Propogate withrdaw to other banches
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropogateDeposit(self, request, context):
        """Propogate deposit to other banches
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=service__pb2.QueryInput.FromString,
                    response_serializer=service__pb2.QueryOutput.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=service__pb2.DepositInput.FromString,
                    response_serializer=service__pb2.Output.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=service__pb2.WithdrawInput.FromString,
                    response_serializer=service__pb2.Output.SerializeToString,
            ),
            'PropogateWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.PropogateWithdraw,
                    request_deserializer=service__pb2.PropogateWithdrawInput.FromString,
                    response_serializer=service__pb2.Output.SerializeToString,
            ),
            'PropogateDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.PropogateDeposit,
                    request_deserializer=service__pb2.PropogateDepositInput.FromString,
                    response_serializer=service__pb2.Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bank.Branch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Branch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.Branch/Query',
            service__pb2.QueryInput.SerializeToString,
            service__pb2.QueryOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.Branch/Deposit',
            service__pb2.DepositInput.SerializeToString,
            service__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.Branch/Withdraw',
            service__pb2.WithdrawInput.SerializeToString,
            service__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PropogateWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.Branch/PropogateWithdraw',
            service__pb2.PropogateWithdrawInput.SerializeToString,
            service__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PropogateDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.Branch/PropogateDeposit',
            service__pb2.PropogateDepositInput.SerializeToString,
            service__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
